### PR TITLE
feat: add  return type on function

### PR DESCRIPTION
**Pull request by ivanyasch**

### CODE REVIEW

**Comment by ivanyasch** [comment]
please update npm version.

**Comment by ert78gb** [comment]
first I have to update other dependencies too. other wise I can't deploy the `npm run build` fails

**Comment by ivanyasch** [comment]
ok, good

**Comment by ert78gb** [comment]
published a new 3.0.0 version. Unfortunately I can't test :(
If you find any issue pls report. thx for the contribution

**Comment by ivanyasch** [comment]
thx for the speed, If I find issue I will let you know.

**Pull request merged**
